const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../葡猪.html'),'utf8');
const start=html.indexOf('const hasItineraryDetailValue =');
const end=html.indexOf('const showShoppingRoute =',start);
const api=vm.runInNewContext(html.slice(start,end)+'\n({hasItineraryDetailValue,hasItineraryFee})');
for(const value of [undefined,null,'','   ']) assert.equal(api.hasItineraryDetailValue(value),false);
for(const value of [0,'0','免費','09:00–18:00']) assert.equal(api.hasItineraryDetailValue(value),true);
assert.equal(api.hasItineraryFee({}),false);
assert.equal(api.hasItineraryFee({ticket:0}),true);
assert.equal(api.hasItineraryFee({ticket:'免費'}),true);
assert.equal(api.hasItineraryFee({settlementTwdAmount:0}),true);
assert.equal(api.hasItineraryFee({isPaid:true,payer:'旅伴'}),true);
const sample={time:'07:30',activity:'交通',ticket:'',openTime:'',note:'保留備註'};
const before=JSON.stringify(sample);api.hasItineraryFee(sample);api.hasItineraryDetailValue(sample.openTime);assert.equal(JSON.stringify(sample),before);
assert(html.includes('v-if="!isReadOnly || hasItineraryFee(item) || hasItineraryDetailValue(item.openTime)"'));
assert(html.includes('v-else-if="hasItineraryFee(item)"'));
assert(html.includes('v-else-if="hasItineraryDetailValue(item.openTime)"'));
assert(html.includes('v-model="item.time" type="time"'));
assert(html.includes('v-model="item.ticket"'));assert(html.includes('v-model="item.openTime"'));
console.log('PASS blank/filled details, zero/free fees, payment metadata retained, readonly visibility, editable fields and top start time preserved.');
