const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../葡猪.html'),'utf8');
const start=html.indexOf('const hasItineraryDetailValue =');
const end=html.indexOf('const showShoppingRoute =',start);
const api=vm.runInNewContext(html.slice(start,end)+'\n({hasItineraryDetailValue,hasItineraryFee})');
for(const value of [undefined,null,'','   ']) assert.equal(api.hasItineraryDetailValue(value),false);
for(const value of [0,'0','免費','09:00–18:00']) assert.equal(api.hasItineraryDetailValue(value),true);
assert.equal(api.hasItineraryFee({}),false);
assert.equal(api.hasItineraryFee({ticket:0}),true);
assert.equal(api.hasItineraryFee({ticket:'免費'}),true);
assert.equal(api.hasItineraryFee({settlementTwdAmount:0}),true);
assert.equal(api.hasItineraryFee({isPaid:true,payer:'旅伴'}),true);
const sample={time:'07:30',activity:'交通',ticket:'',openTime:'',note:'保留備註'};
const before=JSON.stringify(sample);api.hasItineraryFee(sample);api.hasItineraryDetailValue(sample.openTime);assert.equal(JSON.stringify(sample),before);
assert(html.includes("(!isReadOnly && (isItineraryFieldOpen(item, 'fee') || isItineraryFieldOpen(item, 'time'))"));
assert(html.includes('v-else-if="isReadOnly && hasItineraryFee(item)"'));
assert(html.includes('v-else-if="isReadOnly && hasItineraryDetailValue(item.openTime)"'));
assert(html.includes('v-model="item.time" type="time"'));
assert(html.includes('v-model="item.ticket"'));assert(html.includes('v-model="item.openTime"'));
assert(html.includes('itinerary-title-readonly'));assert(html.includes('itinerary-note-readonly'));
assert(html.includes('>開始</span>'));assert(html.includes('>時間資訊</span>'));
assert(html.includes('aria-label="新增費用欄位"'));assert(html.includes('aria-label="新增時間資訊欄位"'));
const uiStart=html.indexOf('const itineraryFieldExpansion =');
const uiEnd=html.indexOf('const vaultEnvelope =',uiStart);
const context={reactive:x=>x,currentTripId:{value:'trip-A'},currentDay:{value:{fullDate:'2026-10-28',items:[sample]}},isReadOnly:{value:false},resizeAllTextareas(){},...api};
const ui=vm.runInNewContext(html.slice(uiStart,uiEnd)+'\n({isItineraryFieldOpen,setItineraryFieldOpen,clearItineraryFieldExpansion})',context);
assert.equal(ui.isItineraryFieldOpen(sample,'fee'),false);
ui.setItineraryFieldOpen(sample,'fee',true);assert.equal(ui.isItineraryFieldOpen(sample,'fee'),true);
assert.equal(JSON.stringify(sample),before); // Expanding a field must not change shared data.
sample.id='stable';ui.setItineraryFieldOpen(sample,'time',true);
assert.equal(ui.isItineraryFieldOpen({...sample},'time'),true); // Survives a sync-cloned card.
context.currentTripId.value='trip-B';assert.equal(ui.isItineraryFieldOpen(sample,'time'),false);
context.currentTripId.value='trip-A';context.currentDay.value.fullDate='2026-10-29';assert.equal(ui.isItineraryFieldOpen(sample,'time'),false);
context.currentDay.value.fullDate='2026-10-28';ui.clearItineraryFieldExpansion();
context.isReadOnly.value=true;ui.setItineraryFieldOpen(sample,'fee',true);assert.equal(ui.isItineraryFieldOpen(sample,'fee'),false);
assert.equal(ui.isItineraryFieldOpen({ticket:0},'fee'),true);assert.equal(ui.isItineraryFieldOpen({openTime:'入場 13:50–14:20'},'time'),true);
console.log('PASS wrapped reading text, distinct time labels, optional fields, zero/free/paid values, lock guard and stable UI-only expansion.');
